AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  S3WithReplaceHeader:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [ !Ref AWS::StackName, "s3-header-replace"]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  AnonymiserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: anonymizer.handler
      Runtime: nodejs12.x
      Policies:
      - AmazonS3FullAccess
      - CloudWatchFullAccess
      Events:
        ReplaceHeaderEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3WithReplaceHeader
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .html

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt AnonymiserFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt S3WithReplaceHeader.Arn

Outputs:
  AnonymiserFunction:
    Description: "Anonymiser Lambda Function ARN"
    Value: !GetAtt AnonymiserFunction.Arn